version: '3.9'

networks:
  dockerize:
    driver: bridge

services:
  mysql:
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: ${PROJECT_NAME:-docker}-mysql
    env_file: .env
    hostname: mysql
    image: mysql:8-debian
    ports:
      - "${MYSQL_PORT}:3306"
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=${MYSQL_ROOT_PASSWORD} --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  app:
    container_name: ${PROJECT_NAME:-docker}-webserver
    image: ${REGISTRY:-elioseverojunior/dockerize}:${TAG:-latest}
    restart: unless-stopped
    hostname: webserver
    env_file: .env
    environment:
      - DB_HOST=${MYSQL_HOST}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_PORT=${MYSQL_PORT}
    ports:
      - "${HTTP_PORT}:8080"
    volumes:
      - ./src:/app/src
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "mysql" ]
      timeout: 20s
      retries: 10
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql:mysql

volumes:
  mysql-data:
