---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: webserver-assessment
  labels:
    app: dockerize
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: webserver-assessment
  labels:
    app: dockerize
spec:
  ports:
    - port: 3306
  selector:
    app: dockerize
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: webserver-assessment
  labels:
    app: dockerize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockerize
  template:
    metadata:
      labels:
        app: dockerize
    spec:
      containers:
        - image: mysql:8-debian
          name: mysql
          envFrom:
            - secretRef:
                name: database-secrets
          ports:
            - containerPort: 3306
              name: mysql
              protocol: TCP
          #          lifecycle:
          #            postStart:
          #              exec:
          #                command: [ "/bin/sh", "-c", "ls -lha /tmp/ && /tmp/init-sql-db.sh && cat /tmp/deploy_init.sql && rm -rf /tmp/deploy_init.sql;" ]
          livenessProbe:
            exec:
              command:
                - /opt/healthcheck-liveness.sh
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          #          readinessProbe:
          #            exec:
          #              command:
          #                - /opt/healthcheck-readiness.sh
          #            initialDelaySeconds: 5
          #            periodSeconds: 2
          #            timeoutSeconds: 1
          #            successThreshold: 1
          #            failureThreshold: 3
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: executable-scripts
              mountPath: /tmp/init-sql-db.sh
              subPath: init-sql-db.sh
              readOnly: false
            - name: executable-scripts
              mountPath: /opt/healthcheck-liveness.sh
              subPath: healthcheck-liveness.sh
              readOnly: false
            - name: executable-scripts
              mountPath: /opt/healthcheck-readiness.sh
              subPath: healthcheck-readiness.sh
              readOnly: false
            - name: mysql-scripts
              mountPath: /tmp/init.sql
              subPath: init.sql
              readOnly: false
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
        - name: executable-scripts
          configMap:
            name: executable-scripts
            items:
              - key: init-sql-db.sh
                path: init-sql-db.sh
              - key: healthcheck-liveness.sh
                path: healthcheck-liveness.sh
              - key: healthcheck-readiness.sh
                path: healthcheck-readiness.sh
            defaultMode: 0755
        - name: mysql-scripts
          configMap:
            name: mysql-scripts
            items:
              - key: init.sql
                path: init.sql
            defaultMode: 0644
      dnsPolicy: ClusterFirst
