---
apiVersion: v1
kind: Service
metadata:
  name: dockerize
  namespace: webserver-assessment
  labels:
    app: dockerize
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: dockerize
