---
apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: webserver-assessment
  labels:
    app: dockerize
type: Opaque
stringData:
  server.config: |-
    blogpost_user:@blogpostP@ssw0rd@tcp(mysql:3306)/blog
data:
  MYSQL_ROOT_USER: cm9vdA==
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_USER: YmxvZ3Bvc3RfdXNlcg==
  MYSQL_PASSWORD: QGJsb2dwb3N0UEBzc3cwcmQ=
  MYSQL_DATABASE: YmxvZw==
  MYSQL_HOST: bXlzcWw=
  MYSQL_PORT: MzMwNg==
